[manifest]
version = "1.0.0"
priority = 0

# Add Legendary to Joker ObjectType
# (Thank you @tecci from the Balatro Discord)
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
pattern = '''
{ key = "Common" },
{ key = "Uncommon" },
{ key = "Rare" },
'''
position = "after"
payload = '''{ key = "Legendary" }, '''
match_indent = true
times = 1
