name: Publish Release on Tag Creation

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  makerelease:
    runs-on: ubuntu-latest

    steps:
      - name: Print what triggered this
        run: "echo $GITHUB_REF"
        env:
          GITHUB_REF: ${{ github.ref }}
      
      - name: Get Repository Files
        uses: actions/checkout@v4
        with:
          path: 'alleemod'
      
      - name: Make Sure Files Exist
        run: 'echo "Hello World"'
