name: Publish Release on Tag Creation

on:
  push:
    tags:
      - '*'

jobs:
  makerelease:
    runs-on: ubuntu-latest

    steps:
      - name: Print what triggered this
        # if: startsWith(github.ref, 'refs/tags/')
        run: "echo $GITHUB_REF"
        env:
          GITHUB_REF: ${{ github.ref }}
      
      - name: Get Repository Files
        # if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v4
        with:
          path: 'alleemod'
      
      - name: Make Sure Files Exist
        # if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd alleemod
          ls
